-- Run this against your MySQL database
-- 1. Make ID_CAJA nullable (allows "ahorro" gastos not linked to any caja)
ALTER TABLE GASTO DROP FOREIGN KEY FK_GASTO_CAJA_ID_CAJA;
ALTER TABLE GASTO MODIFY COLUMN ID_CAJA INT NULL;
ALTER TABLE GASTO ADD CONSTRAINT FK_GASTO_CAJA_ID_CAJA FOREIGN KEY (ID_CAJA) REFERENCES CAJA(ID_CAJA) ON DELETE RESTRICT;

-- 2. Add ANULADO column for soft-delete of gastos
ALTER TABLE GASTO ADD COLUMN ANULADO TINYINT(1) NOT NULL DEFAULT 0;

-- 3. Add ID_USUARIO column to track who created the gasto
ALTER TABLE GASTO ADD COLUMN ID_USUARIO INT NULL;
ALTER TABLE GASTO ADD CONSTRAINT FK_GASTO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE RESTRICT;

-- 4. Create CATEGORIA_GASTO table
CREATE TABLE CATEGORIA_GASTO (
    ID_CATEGORIA_GASTO INT NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR(100) NOT NULL,
    ACTIVO TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (ID_CATEGORIA_GASTO)
);
