-- ============================================================
-- Seed data para PosWeb (MySQL)
-- Ejecutar después de: dotnet ef database update
-- USO: & "C:\Program Files\MySQL\MySQL Server 8.4\bin\mysql" -u root -D posweb < seed.sql
-- ============================================================

-- ============================================================
-- UNIDADES DE MEDIDA (las basicas UNIDAD, KILO, L vienen de la migration)
-- ============================================================
INSERT INTO UNIDAD_MEDIDA (ID_UNIDAD_MEDIDA, COD_UNIDAD_MEDIDA, DESC_UNIDAD_MEDIDA)
SELECT 4, 'ML', 'Mililitros'
WHERE NOT EXISTS (SELECT 1 FROM UNIDAD_MEDIDA WHERE ID_UNIDAD_MEDIDA = 4);

INSERT INTO UNIDAD_MEDIDA (ID_UNIDAD_MEDIDA, COD_UNIDAD_MEDIDA, DESC_UNIDAD_MEDIDA)
SELECT 5, 'GR', 'Gramos'
WHERE NOT EXISTS (SELECT 1 FROM UNIDAD_MEDIDA WHERE ID_UNIDAD_MEDIDA = 5);

-- ============================================================
-- CATEGORIAS
-- ============================================================
INSERT INTO CATEGORIA (ID_CATEGORIA, COD_CATEGORIA, DESC_CATEGORIA)
SELECT 1, 'ALIMENTOS', 'Alimentos y Comestibles'
WHERE NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE ID_CATEGORIA = 1);

INSERT INTO CATEGORIA (ID_CATEGORIA, COD_CATEGORIA, DESC_CATEGORIA)
SELECT 2, 'BEBIDAS', 'Bebidas'
WHERE NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE ID_CATEGORIA = 2);

INSERT INTO CATEGORIA (ID_CATEGORIA, COD_CATEGORIA, DESC_CATEGORIA)
SELECT 3, 'LIMPIEZA', 'Limpieza'
WHERE NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE ID_CATEGORIA = 3);

INSERT INTO CATEGORIA (ID_CATEGORIA, COD_CATEGORIA, DESC_CATEGORIA)
SELECT 4, 'LACTEOS', 'Lácteos y Derivados'
WHERE NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE ID_CATEGORIA = 4);

INSERT INTO CATEGORIA (ID_CATEGORIA, COD_CATEGORIA, DESC_CATEGORIA)
SELECT 5, 'PERFUMERIA', 'Perfumería e Higiene'
WHERE NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE ID_CATEGORIA = 5);

INSERT INTO CATEGORIA (ID_CATEGORIA, COD_CATEGORIA, DESC_CATEGORIA)
SELECT 6, 'ALMACEN', 'Almacén'
WHERE NOT EXISTS (SELECT 1 FROM CATEGORIA WHERE ID_CATEGORIA = 6);

-- ============================================================
-- PRODUCTOS (UNIDAD_MEDIDA: 1=UNIDAD, 2=KILO, 3=L, 4=ML, 5=GR)
-- ============================================================
INSERT INTO PRODUCTO (COD_PRODUCTO, CODIGO_BARRAS, DESC_PRODUCTO, PRECIO, COSTO, ID_CATEGORIA, ID_UNIDAD_MEDIDA, CONTENIDO, MARCA, FECHA_ALTA, FECHA_ULTIMA_MOD, ACTIVO)
SELECT 'P001', '7790000000001', 'Arroz Largo Fino 1kg', 1200.00, 900.00, 1, 2, 1.00, 'Gallo', NOW(), NOW(), TRUE
WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE COD_PRODUCTO = 'P001');

INSERT INTO PRODUCTO (COD_PRODUCTO, CODIGO_BARRAS, DESC_PRODUCTO, PRECIO, COSTO, ID_CATEGORIA, ID_UNIDAD_MEDIDA, CONTENIDO, MARCA, FECHA_ALTA, FECHA_ULTIMA_MOD, ACTIVO)
SELECT 'P002', '7790000000002', 'Aceite Girasol 900ml', 1800.00, 1350.00, 1, 3, 0.90, 'Cocinero', NOW(), NOW(), TRUE
WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE COD_PRODUCTO = 'P002');

INSERT INTO PRODUCTO (COD_PRODUCTO, CODIGO_BARRAS, DESC_PRODUCTO, PRECIO, COSTO, ID_CATEGORIA, ID_UNIDAD_MEDIDA, CONTENIDO, MARCA, FECHA_ALTA, FECHA_ULTIMA_MOD, ACTIVO)
SELECT 'P003', '7790000000003', 'Gaseosa Cola 1.5L', 1500.00, 1100.00, 2, 3, 1.50, 'Coca-Cola', NOW(), NOW(), TRUE
WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE COD_PRODUCTO = 'P003');

INSERT INTO PRODUCTO (COD_PRODUCTO, CODIGO_BARRAS, DESC_PRODUCTO, PRECIO, COSTO, ID_CATEGORIA, ID_UNIDAD_MEDIDA, CONTENIDO, MARCA, FECHA_ALTA, FECHA_ULTIMA_MOD, ACTIVO)
SELECT 'P004', '7790000000004', 'Agua Mineral 2L', 800.00, 550.00, 2, 3, 2.00, 'Villavicencio', NOW(), NOW(), TRUE
WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE COD_PRODUCTO = 'P004');

INSERT INTO PRODUCTO (COD_PRODUCTO, CODIGO_BARRAS, DESC_PRODUCTO, PRECIO, COSTO, ID_CATEGORIA, ID_UNIDAD_MEDIDA, CONTENIDO, MARCA, FECHA_ALTA, FECHA_ULTIMA_MOD, ACTIVO)
SELECT 'P005', '7790000000005', 'Detergente 500ml', 950.00, 700.00, 3, 3, 0.50, 'Skip', NOW(), NOW(), TRUE
WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE COD_PRODUCTO = 'P005');

INSERT INTO PRODUCTO (COD_PRODUCTO, CODIGO_BARRAS, DESC_PRODUCTO, PRECIO, COSTO, ID_CATEGORIA, ID_UNIDAD_MEDIDA, CONTENIDO, MARCA, FECHA_ALTA, FECHA_ULTIMA_MOD, ACTIVO)
SELECT 'P006', '7790000000006', 'Leche Entera 1L', 1100.00, 800.00, 4, 3, 1.00, 'La Serenísima', NOW(), NOW(), TRUE
WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE COD_PRODUCTO = 'P006');

INSERT INTO PRODUCTO (COD_PRODUCTO, CODIGO_BARRAS, DESC_PRODUCTO, PRECIO, COSTO, ID_CATEGORIA, ID_UNIDAD_MEDIDA, CONTENIDO, MARCA, FECHA_ALTA, FECHA_ULTIMA_MOD, ACTIVO)
SELECT 'P007', '7790000000007', 'Yogur Bebible Frutilla 200g', 650.00, 450.00, 4, 1, 1.00, 'Sancor', NOW(), NOW(), TRUE
WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE COD_PRODUCTO = 'P007');

INSERT INTO PRODUCTO (COD_PRODUCTO, CODIGO_BARRAS, DESC_PRODUCTO, PRECIO, COSTO, ID_CATEGORIA, ID_UNIDAD_MEDIDA, CONTENIDO, MARCA, FECHA_ALTA, FECHA_ULTIMA_MOD, ACTIVO)
SELECT 'P008', '7790000000008', 'Jabón Tocador x4', 1200.00, 850.00, 5, 1, 1.00, 'Rexona', NOW(), NOW(), TRUE
WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE COD_PRODUCTO = 'P008');

INSERT INTO PRODUCTO (COD_PRODUCTO, CODIGO_BARRAS, DESC_PRODUCTO, PRECIO, COSTO, ID_CATEGORIA, ID_UNIDAD_MEDIDA, CONTENIDO, MARCA, FECHA_ALTA, FECHA_ULTIMA_MOD, ACTIVO)
SELECT 'P009', '7790000000009', 'Fideos Spaghetti 500g', 700.00, 500.00, 6, 2, 0.50, 'Matarazzo', NOW(), NOW(), TRUE
WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE COD_PRODUCTO = 'P009');

INSERT INTO PRODUCTO (COD_PRODUCTO, CODIGO_BARRAS, DESC_PRODUCTO, PRECIO, COSTO, ID_CATEGORIA, ID_UNIDAD_MEDIDA, CONTENIDO, MARCA, FECHA_ALTA, FECHA_ULTIMA_MOD, ACTIVO)
SELECT 'P010', '7790000000010', 'Galletitas Dulces 200g', 600.00, 400.00, 6, 2, 0.20, 'Oreo', NOW(), NOW(), TRUE
WHERE NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE COD_PRODUCTO = 'P010');

-- ============================================================
-- CLIENTES
-- ============================================================
INSERT INTO CLIENTE (NOMBRE, TIPO_DOCUMENTO, NRO_DOCUMENTO, COD_CLIENTE, TELEFONO, DOMICILIO, MAIL, ACTIVO)
SELECT 'Juan Pérez', 'DNI', '30123456', 'CLI001', '3415550101', 'San Martín 123', 'juan@gmail.com', TRUE
WHERE NOT EXISTS (SELECT 1 FROM CLIENTE WHERE COD_CLIENTE = 'CLI001');

INSERT INTO CLIENTE (NOMBRE, TIPO_DOCUMENTO, NRO_DOCUMENTO, COD_CLIENTE, TELEFONO, DOMICILIO, MAIL, ACTIVO)
SELECT 'María García', 'DNI', '30987654', 'CLI002', '3415550202', 'Belgrano 456', 'maria@gmail.com', TRUE
WHERE NOT EXISTS (SELECT 1 FROM CLIENTE WHERE COD_CLIENTE = 'CLI002');

INSERT INTO CLIENTE (NOMBRE, TIPO_DOCUMENTO, NRO_DOCUMENTO, COD_CLIENTE, TELEFONO, DOMICILIO, MAIL, ACTIVO)
SELECT 'Carlos López', 'DNI', '28555111', 'CLI003', '3415550303', 'Rivadavia 789', 'carlos@hotmail.com', TRUE
WHERE NOT EXISTS (SELECT 1 FROM CLIENTE WHERE COD_CLIENTE = 'CLI003');

INSERT INTO CLIENTE (NOMBRE, TIPO_DOCUMENTO, NRO_DOCUMENTO, COD_CLIENTE, TELEFONO, DOMICILIO, MAIL, ACTIVO)
SELECT 'Ana Martínez', 'DNI', '31222333', 'CLI004', '3415550404', '9 de Julio 321', 'ana@outlook.com', TRUE
WHERE NOT EXISTS (SELECT 1 FROM CLIENTE WHERE COD_CLIENTE = 'CLI004');

-- ============================================================
-- PROVEEDORES
-- ============================================================
INSERT INTO PROVEEDOR (COD_PROVEEDOR, NOMBRE, TIPO_DOCUMENTO, NRO_DOCUMENTO, TELEFONO, DOMICILIO, MAIL, ACTIVO)
SELECT 'PROV001', 'Distribuidora Sur SRL', 'CUIL', '30-12345678-9', '3415551000', 'Av. Pellegrini 1500', 'ventas@distrisur.com', TRUE
WHERE NOT EXISTS (SELECT 1 FROM PROVEEDOR WHERE COD_PROVEEDOR = 'PROV001');

INSERT INTO PROVEEDOR (COD_PROVEEDOR, NOMBRE, TIPO_DOCUMENTO, NRO_DOCUMENTO, TELEFONO, DOMICILIO, MAIL, ACTIVO)
SELECT 'PROV002', 'Alimentos del Centro SA', 'CUIL', '30-87654321-0', '3415552000', 'Bv. Oroño 800', 'contacto@alicentro.com', TRUE
WHERE NOT EXISTS (SELECT 1 FROM PROVEEDOR WHERE COD_PROVEEDOR = 'PROV002');

INSERT INTO PROVEEDOR (COD_PROVEEDOR, NOMBRE, TIPO_DOCUMENTO, NRO_DOCUMENTO, TELEFONO, DOMICILIO, MAIL, ACTIVO)
SELECT 'PROV003', 'Bebidas del Litoral', 'CUIL', '30-11223344-5', '3415553000', 'Córdoba 2500', 'pedidos@bebidaslitoral.com', TRUE
WHERE NOT EXISTS (SELECT 1 FROM PROVEEDOR WHERE COD_PROVEEDOR = 'PROV003');

-- ============================================================
-- SUSCRIPCION + EMPRESA + SUCURSAL (obligatorio para operar)
-- ============================================================
-- Suscripcion (requiere ID_USUARIO=1 admin)
INSERT INTO SUSCRIPCION (ID_SUSCRIPCION, ID_USUARIO_TITULAR, NIVEL, ESTADO, COSTO_MENSUAL, MAX_SUCURSALES, MAX_ADMIN, MAX_USUARIOS, FECHA_INICIO)
SELECT 1, 1, 'Premium', 'Activa', 0, 10, 5, 50, NOW()
WHERE NOT EXISTS (SELECT 1 FROM SUSCRIPCION WHERE ID_SUSCRIPCION = 1);

-- Empresa
INSERT INTO EMPRESA (ID_EMPRESA, NOMBRE, DOCUMENTO, ID_SUSCRIPCION)
SELECT 1, 'Mi Empresa', '30-12345678-9', 1
WHERE NOT EXISTS (SELECT 1 FROM EMPRESA WHERE ID_EMPRESA = 1);

-- Sucursal
INSERT INTO SUCURSAL (ID_SUCURSAL, COD_SUCURSAL, DESC_SUCURSAL, ID_EMPRESA, ACTIVO)
SELECT 1, 'PRINCIPAL', 'Sucursal Principal', 1, TRUE
WHERE NOT EXISTS (SELECT 1 FROM SUCURSAL WHERE ID_SUCURSAL = 1);

-- Actualizar admin: asignar sucursal y activar suscripcion
UPDATE USUARIO SET
    ID_SUCURSAL_DEFAULT = 1,
    SUSCRIPCION_ACTIVA = TRUE
WHERE ID_USUARIO = 1;

-- ============================================================
-- STOCK (productos en sucursal principal)
-- ============================================================
INSERT INTO STOCK_SUCURSAL (ID_PRODUCTO, ID_SUCURSAL, STOCK)
SELECT 1, 1, 50
WHERE NOT EXISTS (SELECT 1 FROM STOCK_SUCURSAL WHERE ID_PRODUCTO = 1 AND ID_SUCURSAL = 1);

INSERT INTO STOCK_SUCURSAL (ID_PRODUCTO, ID_SUCURSAL, STOCK)
SELECT 2, 1, 30
WHERE NOT EXISTS (SELECT 1 FROM STOCK_SUCURSAL WHERE ID_PRODUCTO = 2 AND ID_SUCURSAL = 1);

INSERT INTO STOCK_SUCURSAL (ID_PRODUCTO, ID_SUCURSAL, STOCK)
SELECT 3, 1, 40
WHERE NOT EXISTS (SELECT 1 FROM STOCK_SUCURSAL WHERE ID_PRODUCTO = 3 AND ID_SUCURSAL = 1);

INSERT INTO STOCK_SUCURSAL (ID_PRODUCTO, ID_SUCURSAL, STOCK)
SELECT 4, 1, 60
WHERE NOT EXISTS (SELECT 1 FROM STOCK_SUCURSAL WHERE ID_PRODUCTO = 4 AND ID_SUCURSAL = 1);

INSERT INTO STOCK_SUCURSAL (ID_PRODUCTO, ID_SUCURSAL, STOCK)
SELECT 5, 1, 25
WHERE NOT EXISTS (SELECT 1 FROM STOCK_SUCURSAL WHERE ID_PRODUCTO = 5 AND ID_SUCURSAL = 1);

INSERT INTO STOCK_SUCURSAL (ID_PRODUCTO, ID_SUCURSAL, STOCK)
SELECT 6, 1, 35
WHERE NOT EXISTS (SELECT 1 FROM STOCK_SUCURSAL WHERE ID_PRODUCTO = 6 AND ID_SUCURSAL = 1);

INSERT INTO STOCK_SUCURSAL (ID_PRODUCTO, ID_SUCURSAL, STOCK)
SELECT 7, 1, 20
WHERE NOT EXISTS (SELECT 1 FROM STOCK_SUCURSAL WHERE ID_PRODUCTO = 7 AND ID_SUCURSAL = 1);

INSERT INTO STOCK_SUCURSAL (ID_PRODUCTO, ID_SUCURSAL, STOCK)
SELECT 8, 1, 40
WHERE NOT EXISTS (SELECT 1 FROM STOCK_SUCURSAL WHERE ID_PRODUCTO = 8 AND ID_SUCURSAL = 1);

INSERT INTO STOCK_SUCURSAL (ID_PRODUCTO, ID_SUCURSAL, STOCK)
SELECT 9, 1, 45
WHERE NOT EXISTS (SELECT 1 FROM STOCK_SUCURSAL WHERE ID_PRODUCTO = 9 AND ID_SUCURSAL = 1);

INSERT INTO STOCK_SUCURSAL (ID_PRODUCTO, ID_SUCURSAL, STOCK)
SELECT 10, 1, 30
WHERE NOT EXISTS (SELECT 1 FROM STOCK_SUCURSAL WHERE ID_PRODUCTO = 10 AND ID_SUCURSAL = 1);

-- ============================================================
-- Resumen de lo insertado
-- ============================================================
SELECT '[OK]' AS SEED, CONCAT(COUNT(*), ' productos') AS INFO FROM PRODUCTO
UNION ALL SELECT '[OK]', CONCAT(COUNT(*), ' categorias') FROM CATEGORIA
UNION ALL SELECT '[OK]', CONCAT(COUNT(*), ' clientes') FROM CLIENTE
UNION ALL SELECT '[OK]', CONCAT(COUNT(*), ' proveedores') FROM PROVEEDOR
UNION ALL SELECT '[OK]', CONCAT(COUNT(*), ' sucursales') FROM SUCURSAL;
