import { beforeEach, describe, expect, it, vi } from 'vitest'
import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'

const state = vi.hoisted(() => ({ obtener: vi.fn(), historial: vi.fn(), obtenerPdf: vi.fn(), crearSimple: vi.fn() }))
vi.mock('../../api/client', () => ({ api: { cajaDiaria: state, gastos: { crearSimple: state.crearSimple } } }))
vi.mock('../../components/shared', () => ({ PageShell: ({ title, children, error }: { title: string; children: React.ReactNode; error?: string }) => <main><h1>{title}</h1>{error && <p>{error}</p>}{children}</main> }))
vi.mock('../../components/ui/Dialog', () => ({ default: ({ open, title, children, footer }: { open: boolean; title: string; children: React.ReactNode; footer: React.ReactNode }) => open ? <div role="dialog" aria-label={title}><h2>{title}</h2>{children}{footer}</div> : null }))
const caja = { fecha: '2026-08-17', totalIngresos: 500000, totalEgresos: 65000, resultado: 435000, cantidadEventosRealizados: 1, ingresos: [{ fechaRegistro: '2026-08-17T18:00:00', nombreCliente: 'Ana', tipoEvento: 'Boda', medioPago: 'Transferencia', monto: 500000, tipo: 'Pago de evento' }], egresos: [{ fecha: '2026-08-17T19:00:00', detalle: 'Hielo', monto: 65000 }], eventosRealizados: [{ horaInicio: '18:00:00', nombreCliente: 'Ana', tipoEvento: 'Boda', estado: 'Pagado' }], desgloseMediosPago: [{ descripcion: 'Transferencia', total: 500000, cantidadPagos: 1 }] }
describe('CajaPage', () => {
 beforeEach(() => { state.obtener.mockReset().mockResolvedValue(caja); state.historial.mockReset().mockResolvedValue([{ fecha: '2026-08-16', totalIngresos: 0, totalEgresos: 0, resultado: 0, cantidadEventosRealizados: 0 }]); state.obtenerPdf.mockReset().mockResolvedValue({ blob: new Blob(['pdf']) }); state.crearSimple.mockReset().mockResolvedValue({}); vi.stubGlobal('open', vi.fn().mockReturnValue({ location: { href: '' }, close: vi.fn() })); URL.createObjectURL = vi.fn().mockReturnValue('blob:pdf'); URL.revokeObjectURL = vi.fn() })
 async function renderPage() { const { default: CajaPage } = await import('../../pages/CajaPage'); return render(<CajaPage />) }
  it('carga resumen y movimientos, y mantiene el historial cerrado hasta solicitarlo', async () => { await renderPage(); expect((await screen.findAllByText('Ingresos')).length).toBeGreaterThan(0); expect(screen.getAllByText('Ana').length).toBeGreaterThan(0); expect(screen.getAllByText('Hielo').length).toBeGreaterThan(0); expect(screen.getAllByText('Transferencia').length).toBeGreaterThan(0); expect(screen.queryByText(/16\/8\/2026/)).not.toBeInTheDocument(); fireEvent.click(screen.getByText('Ver historial')); expect(await screen.findByRole('dialog', { name: 'Historial de Caja' })).toBeInTheDocument(); expect(screen.getAllByText(/16\/8\/2026/).length).toBeGreaterThan(0); expect(screen.queryByText('Abrir caja')).not.toBeInTheDocument(); expect(screen.queryByText('Cerrar caja')).not.toBeInTheDocument() })
 it('consulta el detalle al cambiar fecha', async () => { await renderPage(); fireEvent.change(await screen.findByLabelText('Fecha de caja'), { target: { value: '2026-08-16' } }); await waitFor(() => expect(state.obtener).toHaveBeenCalledWith('2026-08-16')) })
 it('mantiene la fecha previa si el selector nativo intenta limpiarla', async () => { await renderPage(); const input = await screen.findByLabelText('Fecha de caja') as HTMLInputElement; fireEvent.change(input, { target: { value: '' } }); expect(input.value).toBe('2026-08-17') })
 it('registra gasto solo con detalle y monto y refresca', async () => { await renderPage(); fireEvent.click(await screen.findByText('Registrar gasto')); fireEvent.change(screen.getByLabelText('Detalle gasto'), { target: { value: 'Hielo' } }); fireEvent.change(screen.getByLabelText('Monto gasto'), { target: { value: '35000' } }); fireEvent.click(within(screen.getByRole('dialog', { name: 'Registrar gasto' })).getByRole('button', { name: 'Registrar gasto' })); await waitFor(() => expect(state.crearSimple).toHaveBeenCalledWith({ detalle: 'Hielo', monto: 35000 })); await waitFor(() => expect(state.obtener.mock.calls.length).toBeGreaterThan(1)) })
  it('muestra un error de carga', async () => { state.obtener.mockRejectedValueOnce(new Error('Sin conexión')); await renderPage(); expect(await screen.findByText('Sin conexión')).toBeInTheDocument() })
  it('solicita y abre el PDF solo al pulsar usando la fecha seleccionada', async () => { await renderPage(); expect(state.obtenerPdf).not.toHaveBeenCalled(); fireEvent.change(await screen.findByLabelText('Fecha de caja'), { target: { value: '2026-08-16' } }); await waitFor(() => expect(state.obtener).toHaveBeenCalledWith('2026-08-16')); fireEvent.click(screen.getByText('Abrir PDF del día')); expect(screen.getByText('Abriendo PDF...')).toBeDisabled(); await waitFor(() => expect(state.obtenerPdf).toHaveBeenCalledWith('2026-08-16')); expect(URL.createObjectURL).toHaveBeenCalled() })
  it('cierra la pestaña temporal y muestra error al fallar el PDF', async () => { const popup = { location: { href: '' }, close: vi.fn() }; vi.stubGlobal('open', vi.fn().mockReturnValue(popup)); state.obtenerPdf.mockRejectedValueOnce(new Error('PDF falló')); await renderPage(); fireEvent.click(await screen.findByText('Abrir PDF del día')); await waitFor(() => expect(popup.close).toHaveBeenCalled()); expect(await screen.findByText('PDF falló')).toBeInTheDocument() })
  it('selecciona una fecha desde historial y cierra el modal', async () => { await renderPage(); fireEvent.click(await screen.findByText('Ver historial')); fireEvent.click((await screen.findAllByText(/16\/8\/2026/))[0]); await waitFor(() => expect(state.obtener).toHaveBeenCalledWith('2026-08-16')); expect(screen.queryByRole('dialog', { name: 'Historial de Caja' })).not.toBeInTheDocument() })
  it('permite cerrar manualmente el historial', async () => { await renderPage(); fireEvent.click(await screen.findByText('Ver historial')); fireEvent.click(screen.getByRole('button', { name: 'Cerrar' })); expect(screen.queryByRole('dialog', { name: 'Historial de Caja' })).not.toBeInTheDocument() })
})
