import { beforeEach, describe, expect, it, vi } from 'vitest'
import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'

const state = vi.hoisted(() => ({ obtener: vi.fn(), historial: vi.fn(), crearSimple: vi.fn() }))
vi.mock('../../api/client', () => ({ api: { cajaDiaria: state, gastos: { crearSimple: state.crearSimple } } }))
vi.mock('../../components/shared', () => ({ PageShell: ({ title, children, error }: { title: string; children: React.ReactNode; error?: string }) => <main><h1>{title}</h1>{error && <p>{error}</p>}{children}</main> }))
vi.mock('../../components/ui/Dialog', () => ({ default: ({ open, title, children, footer }: { open: boolean; title: string; children: React.ReactNode; footer: React.ReactNode }) => open ? <div role="dialog" aria-label={title}><h2>{title}</h2>{children}{footer}</div> : null }))
const caja = { fecha: '2026-08-17', totalIngresos: 500000, totalEgresos: 65000, resultado: 435000, cantidadEventosRealizados: 1, ingresos: [{ fechaRegistro: '2026-08-17T18:00:00', nombreCliente: 'Ana', tipoEvento: 'Boda', medioPago: 'Transferencia', monto: 500000, tipo: 'Pago de evento' }], egresos: [{ fecha: '2026-08-17T19:00:00', detalle: 'Hielo', monto: 65000 }], eventosRealizados: [{ horaInicio: '18:00:00', nombreCliente: 'Ana', tipoEvento: 'Boda', estado: 'Pagado' }], desgloseMediosPago: [{ descripcion: 'Transferencia', total: 500000, cantidadPagos: 1 }] }
describe('CajaPage', () => {
 beforeEach(() => { state.obtener.mockReset().mockResolvedValue(caja); state.historial.mockReset().mockResolvedValue([{ fecha: '2026-08-16', totalIngresos: 0, totalEgresos: 0, resultado: 0, cantidadEventosRealizados: 0 }]); state.crearSimple.mockReset().mockResolvedValue({}) })
 async function renderPage() { const { default: CajaPage } = await import('../../pages/CajaPage'); return render(<CajaPage />) }
 it('carga resumen, movimientos, medio e historial sin controles legacy', async () => { await renderPage(); expect(await screen.findByText('Ingresos')).toBeInTheDocument(); expect(screen.getAllByText((_, node) => node?.tagName === 'P' && node.textContent?.includes('Ana') === true)).toHaveLength(2); expect(screen.getByText((_, node) => node?.tagName === 'P' && node.textContent?.includes('Hielo') === true)).toBeInTheDocument(); expect(screen.getByText(/Transferencia:/)).toBeInTheDocument(); expect(screen.getByText(/16\/8\/2026/)).toBeInTheDocument(); expect(screen.queryByText('Abrir caja')).not.toBeInTheDocument(); expect(screen.queryByText('Cerrar caja')).not.toBeInTheDocument() })
 it('consulta el detalle al cambiar fecha', async () => { await renderPage(); fireEvent.change(await screen.findByLabelText('Fecha de caja'), { target: { value: '2026-08-16' } }); await waitFor(() => expect(state.obtener).toHaveBeenCalledWith('2026-08-16')) })
 it('mantiene la fecha previa si el selector nativo intenta limpiarla', async () => { await renderPage(); const input = await screen.findByLabelText('Fecha de caja') as HTMLInputElement; fireEvent.change(input, { target: { value: '' } }); expect(input.value).toBe('2026-08-17') })
 it('registra gasto solo con detalle y monto y refresca', async () => { await renderPage(); fireEvent.click(await screen.findByText('Registrar gasto')); fireEvent.change(screen.getByLabelText('Detalle gasto'), { target: { value: 'Hielo' } }); fireEvent.change(screen.getByLabelText('Monto gasto'), { target: { value: '35000' } }); fireEvent.click(within(screen.getByRole('dialog', { name: 'Registrar gasto' })).getByRole('button', { name: 'Registrar gasto' })); await waitFor(() => expect(state.crearSimple).toHaveBeenCalledWith({ detalle: 'Hielo', monto: 35000 })); await waitFor(() => expect(state.obtener.mock.calls.length).toBeGreaterThan(1)) })
 it('muestra un error de carga', async () => { state.obtener.mockRejectedValueOnce(new Error('Sin conexión')); await renderPage(); expect(await screen.findByText('Sin conexión')).toBeInTheDocument() })
})
